[functions]
  directory = "apps/api/netlify/functions"
  node_bundler = "esbuild"

  external_node_modules = [
    "@prisma/client",
    "@prisma/adapter-pg",
    "pg"
  ]

  included_files = [
    "node_modules/@prisma/client/runtime/**"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[functions.api]
  ignored_node_modules = [
    "@nestjs/microservices",
    "@nestjs/websockets"
  ]